name: Continuous Integration
on:
  schedule:
    - cron: "15 * * * *"
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    env: 
      CI_COMMIT_MESSAGE: Continuous Integration Build Artifacts
      CI_COMMIT_AUTHOR: Continuous Integration
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v2
      with:
        python-version: 3.8 
    - name: python setup
      run: pip install requests && cd srv/ && python fetch.v2.py

    # Commit and push all changed files.
    - name: GIT Commit
      # Only run on main branch push (e.g. after pull request merge).
      run: |
        git config --global user.name "${{ env.CI_COMMIT_AUTHOR }}"
        git config --global user.email "username@users.noreply.github.com"
        git commit -a -m "${{ env.CI_COMMIT_MESSAGE }}"
        git push
